#!/bin/bash
# A simple script to generate opencart extension
rm -r ./upload
rm oc-2.3.x-cardinity-1.0.1.ocmod.zip
cd system/library/cardinity
composer install
cd ../../../
mkdir ./upload
cp -R admin ./upload/admin
cp -R catalog ./upload/catalog
cp -R system ./upload/system
cp install.xml ./upload/install.xml
zip -r oc-2.3.x-cardinity-1.0.1.ocmod.zip upload

